// Generated by CoffeeScript 2.7.0
(function() {
  // Place all the behaviors and hooks related to the matching controller here.
// All this logic will automatically be available in application.js.
// You can use CoffeeScript in this file: http://coffeescript.org/


}).call(this);
